### ISSUE TITLE
Option of update_default_version

### ISSUE THREAD

**Issue by Dogers** [HENNGE/terraform-aws-autoscaling-mixed-instances#15]
Currently when the launch template gets updated (new userdata, EBS specs or whatever) a new version of the launch template is made, but the default in use version of the template stays at the initial version 1. The AWS console has to be used to change the default version, after which the instances can be terminated to pick up the new version (or left until the lifetime is up).

Adding a variable for the [update_default_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#update_default_version) param should provide the option to make this part automatic?

**Comment by michaelaw320** [comment]
Default behaviour of this module is to always point to `Latest` version.

However, we did in https://github.com/HENNGE/terraform-aws-autoscaling-mixed-instances/pull/12 add a convenience flag to update launch template using numbered version [`use_created_lt_latest_version`](https://github.com/HENNGE/terraform-aws-autoscaling-mixed-instances#input_use_created_lt_latest_version) to solve the problem before `update_default_version` exists.

Thank you for raising this issue

**Comment by Dogers** [comment]
Hmm, that doesn't seem to be happening from what I can see - I'll do some more digging, maybe it's something we're doing to it!

**Comment by michaelaw320** [comment]
Confirmed the issue, on `Launch Template` console, the Default is not updated to the latest numbered version
But when using Autoscaling Group, Autoscaling Group points to `Latest` as the default thus will pick up the "correct version" of launch template

**Comment by Dogers** [comment]
I think this was down to the wrapper we were putting around the module! Apologies :)
